organization:
  name: Connecteam

app:
  title: Connecteam
  baseUrl: https://backstage-poc.internal.connecteam.com/

auth:
  providers:
    github:
      development:
        clientId: "Ov23liuHSNOa6MsYUU96"
        clientSecret: "dc7d1fef14a6beec653e69d3ea75b82f38b48e65"
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

backend:
  baseUrl: https://backstage-poc.internal.connecteam.com/
  listen:
    port: 7007

    database:
      client: pg
      connection:
        host: 'backstage-postgresql'
        port: '5432'
        user: 'bn_backstage'
        password: 'sdlksdlkjlkncsdsdc'

techdocs:
  publisher:
    type: local
  storageUrl: http://localhost:7007/api/techdocs/static/docs

permission:
  enabled: true

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: master
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ./examples/entities.yaml

    # Local example template
    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]